# Generated by Django 4.0.2 on 2022-03-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='uid',
            new_name='id',
        ),
    ]
